### ISSUE TITLE
Set the structure of the project up

### ISSUE THREAD

**Issue by MatheusMartino97** [Condo-Mini/condo_mini-api#1]
# Tasks

## Code base

- [x] Define directories structure for the project
- [x] Set up the express
- [x] Set up the mongoose connection

## Documentation

- [x] Define branches pattern
